# Site settings
author: Manny Baez 
title: Code Red
header-img: img/home-bg.png
email: jesusmbaez@gmail.com
copyright_name: Manny Baez 
description: > # this means to ignore newlines until "baseurl:"
  From RN to Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jesusmbaez

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
