# Site settings
author: Jesus "Manny" Baez
title: 
header-img: img/home-bg.png
email: jesusmbaez@gmail.com
copyright_name: Jesus "Manny" Baez
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: thebeatsalive
github_username:  jesusmbaez

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
